- type: slack-rtm-input
- type: slack-storage
  source: slack-rtm-input
  config:
    table: slack_rtm
- type: slack-output
  config:
    table: slack_rtm
    poll-frequency: 10m
- type: calendar-input
  config:
    poll-frequency: 30m
- type: calendar-storage
  source: calendar-input
  config:
    table: calendar_events
- type: slack-output
  config:
    table: calendar_events
    poll-frequency: 5m
